apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary
    app: myapp  # Key value paids
spec:
  containers: # List
    - name: myapp
      # image: stacksimplify/kubenginx:1.0.0 # kubectl run my-first-pod --image avts/nginxvivek:v1
      image: avts/nginxvivek:v2
      ports: 
        - containerPort: 80


    